version: '3.5'
  
services:
  ann:
   image: indrajeet3333/ann:latest
   ports:
     - 5000:5000
   deploy:
     mode: replicated
     replicas: 20
     placement:
      constraints: [node.role == worker]
   networks:
    - ingress

  proxy:
    image: sushruth13/miller-proxy:latest
    ports:
      - 81:80
    depends_on:
      - ann
    deploy:
      placement:
        constraints: [node.role==manager]
    networks:
      - ingress
networks:
     balance:
       driver: ingress