version: '3'

services:
  prometheus:
   image: sushruth13/customprom
   ports:
      - 9090:9090
   deploy:
      replicas: 1
      restart_policy:
        max_attempts: 10
        condition: on-failure
      placement:
        constraints: [node.role==manager]
   networks:
      - balance
networks:
  balance:
    driver: overlay